-- ============================================================================
-- SQL SCRIPT: Remove Problematic Abbreviations
-- Generated by: remove_token_abbreviations_v2.py
-- Strategy: Remove abbreviations whose keys match place name tokens
-- ============================================================================

-- IMPORTANT: Backup your database before running this script!
-- Execute in transaction mode for safety:
--   BEGIN TRANSACTION;
--   <run this script>
--   ROLLBACK;  -- to undo, or COMMIT; to apply

-- Total problematic keys: 308
-- Total records to be removed: 1,880

-- Delete all abbreviations with problematic keys
DELETE FROM abbreviations
WHERE key IN (
    'an', 'ha', 'ho', 'en', 'tha', 'han', 'hanh', 'la', 'phu', 'ta',
    'k', 'ba', 'ia', 'am', 'thanh', 'do', 'don', 'na', 'ca', 'dong',
    'du', 'thu', 'da', 'tan', 'di', 'ni', 'cha', 'vinh', 'tho', 'no',
    'tu', 'xu', 'tra', 'pho', 'thai', 'my', 'va', 'lu', 'phong', 'van',
    'thua', 'ban', 'thuan', 'lan', 'ma', 'ga', 'kha', 'ap', 'huc', 'lang',
    'lam', 'mo', 'can', 'go', 'co', 'chu', 'tam', 'ro', 'hue', 'cam',
    'trang', 'thuong', 'nha', 'dan', 'et', 'bai', 'sa', 'tuyen', 'thang', 'ky',
    'lak', 'bo', 'nai', 'rong', '1', 'con', 'hap', 'thap', 'ka', 'pa',
    'xa', 'nho', 'cong', 'to', 'ham', 'ko', 'kan', 'kon', 'mai', 'pha',
    'chuong', 'krong', 'hat', 'cho', 'nan', 'ly', 'tau', 'thoi', 'cat', 'que',
    'vo', 'hieu', 'me', 'chien', 'thong', 'nhan', 'gan', 'thien', 'man', 'phan',
    'kho', 'chanh', '3', 'dun', 'nu', '4', 'dung', '5', 'phung', 'khoa',
    '8', 'dang', 'eo', 'ar', '6', 'dam', 'tuan', 'lanh', 'thieu', '7',
    'ton', 'san', 'mang', 'nhuan', '10', '11', 'nhai', 'pac', 'khai', 'chai',
    'pu', 'hy', 'xin', 'lat', 'thao', 'tai', 'ayun', 'pleiku', '12', 'quyen',
    'gao', 'xat', 'pro', 'chua', 'it', 'vuong', 'tong', 'chieu', 'not', 'chung',
    'pham', 'ne', 'nham', 'kbang', 'nt', 'pah', 'phien', 'al', 'nua', 'm''drak',
    'tanh', 'grai', 'dac', 'plo', '14', 'pan', '05', '01', '13', 'khoi',
    '03', '07', 'glong', '04', '02', 'plong', 'dich', '15', 'pi', '09',
    '06', '08', 'puh', 'goi', 'ty', 'dro', 'pe', 'nhue', 'phai', 'nau',
    'doai', '16', 'khau', 'nen', 'danh', 'nhuong', 'vam', 'drong', 'pung', 'bla',
    'hum', '17', 'xan', 'troi', 'bha', 'xe', 'bam', 'pal', 'khong', 'thuc',
    'blang', 'vy', 'voi', '18', 'sro', 'lia', 'nhung', '25', 'kroong', 'xang',
    'nhien', 'hla', 'pam', 'chang', 'phoi', '20', 'thung', 'pla', 'hlo', 'kno',
    '19', 'xop', 'bhang', 'uar', 'tat', 'nanh', 'blu', 'toai', 'nenh', 'nhieu',
    'buoi', 'phao', 'xeo', 'hra', 'dy', 'klang', 'ch''om', 'chac', 'chaval', 'glar',
    'dle', 'ealy', 'bhalle', 'luyen', '27', 'sia', 'hnol', 'd''ran', '28', 'b''lao',
    'tr''hy', 'dacpree', 'xen', 'dongvien', 'dar', 'glai', 'pau', 'grang', 'plao', 'prao',
    'nhoi', 'nghen', 'vii', 'chue', 'neo', 'xy', 'ladee', 'eatrol', 'pxi', 'knang',
    'iv', 'laee', 'iii', 'eabar', 'dacpring', '21', 'kep', '24', '22', 'eabia',
    '26', 'lim', 'nhau', 'zuoih', 'zuoich', 'klong', 'pet', 'xim'
);

-- Verify removal
SELECT COUNT(*) as remaining_count FROM abbreviations;
