-- SQL Script to Remove Problematic Abbreviations
-- Generated by remove_token_abbreviations.py
--
-- Logic: Remove abbreviations that are actual tokens in place names
--

BEGIN TRANSACTION;

-- Statistics BEFORE removal
SELECT 'BEFORE' as timing,
       COUNT(*) FILTER (WHERE ward_abbreviation IS NOT NULL) as ward_count,
       COUNT(*) FILTER (WHERE district_abbreviation IS NOT NULL) as district_count,
       COUNT(*) FILTER (WHERE province_abbreviation IS NOT NULL) as province_count
FROM admin_divisions;

-- Ward level abbreviations removal
-- Removing 134 ward abbreviations
UPDATE admin_divisions
SET ward_abbreviation = NULL
WHERE ward_abbreviation IN ('nt', 'ta', 'ha', 'al', 'an', 'la', 'da', 'ty', 'ba', 'et', 'na', 'dy', 'ca', 'tu', 'ma', 'ka', 'va', 'du', 'ap', 'li', 'do', 'it', 'pa', 'tha', 'ho', 'ky', 'hy', 'co', 'en', 'so', 'to', 'bi', 'ga', 'xa', 'sa', 'nu', 'vy', 'ar', 'ly', 'di', 'vo', 'ne', 'vi', 'thi', 'pu', 'hu', 'cha', 'tat', 'iv', 'xy', 'my', 'me', 'gi', 'dac', 'si', 'am', 'tru', 'phu', 'bu', '1', '10', '12', '13', '14', '15', '2', '4', '6', '8', '9', '11', '16', '3', '5', '7', '18', 'ro', '17', '19', '22', '25', '26', '27', '28', 'pla', 'lat', 'nan', 'lu', 'ke', 'cat', 'ia', 'tra', 'bo', 'phi', 'i', 'ii', 'v', 'can', 'ni', 'pe', 'dro', 'ko', 'go', 'ea', 'tan', 'gia', 'mi', 'pho', 'lo', 'thu', 'mo', 'no', 'tri', 'kho', 'cam', 'eo', '05', '06', '07', '08', '01', '02', '04', '09', '03', '21', '24', 'pah', 'chi', 'hoa', 'pha', '20', 'don', 'bha');

-- District level abbreviations removal
-- Removing 35 district abbreviations
UPDATE admin_divisions
SET district_abbreviation = NULL
WHERE district_abbreviation IN ('nt', 'ha', 'ta', 'ty', 'vy', 'al', 'to', 'da', 'ka', 'ap', 'tu', 'ba', 'hy', '1', '10', '11', '12', '3', '4', '5', '6', '7', '8', 'bi', 'an', 'my', 'am', 'vi', 'ho', 'so', 'ly', 'ma', 'kan', 'la', '9');

-- Province level abbreviations removal
-- Removing 5 province abbreviations
UPDATE admin_divisions
SET province_abbreviation = NULL
WHERE province_abbreviation IN ('hu', 'hy', 'la', 'na', 'nt');

-- Statistics AFTER removal
SELECT 'AFTER' as timing,
       COUNT(*) FILTER (WHERE ward_abbreviation IS NOT NULL) as ward_count,
       COUNT(*) FILTER (WHERE district_abbreviation IS NOT NULL) as district_count,
       COUNT(*) FILTER (WHERE province_abbreviation IS NOT NULL) as province_count
FROM admin_divisions;

COMMIT;